<?php echo $this->doctype(); 
$currentSelecteLang = "en";
?>
<html lang="<?php echo $currentSelecteLang;?>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="andre marcelo informatica">
    <meta name="keywords" content="andremarcelo,andre marcelo,rocket,Java, android developer">
    <meta name="author" content="andre marcelo">
    
        <?php echo $this->headTitle($this->t('mteixeira.index.title')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                                        ->prependStylesheet($this->basePath() . '/assets/css/docs.css')        
                ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/vendor/bootstrap/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/vendor/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/js/page.js')
            ->prependFile($this->basePath() . '/vendor/zoom/jquery.elevateZoom-3.0.6.min.js')
            ->prependFile($this->basePath() . '/vendor/jquery/jquery-1.10.2.min.js')
            ->prependFile($this->basePath() . '/vendor/bootstrap/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/vendor/bootstrap/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
  <body>