<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><?php echo $this->title;?></div>
    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th><?php echo $this->t('tecs.name');?></th>
                <th><?php echo $this->t('tecs.level');?></th>
                <th<?php echo $this->t('tecs.years');?><</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tec as $tecs):?>
            <tr>
                <td class="bold"><?php echo $tecs[0]; ?></td>
                <td><?php echo $tecs[1]; ?></td>
                <td><?php echo $tecs[2]; ?></td>
            </tr>
          <?php endforeach;?>
        </tbody>
    </table>
</div>