<div class="row">
    <div class="col-md-12" role="main">
        <div class="bs-docs-section">
            <div class="page-header">
                <h1 id="contacts"><?php echo ucfirst($this->t('contacts.title')); ?></h1>
            </div>
            <blockquote>
                <p class="lead"><?php echo $this->t('contacts.text'); ?></p>
            </blockquote>
        </div>
        <address>
            <strong>Andre Marcelo</strong><br>
            Rua Ruben A, 137, 8 Drt<br>
            Lordelo - Porto Portugal<br>
            <abbr title="Phone">P:</abbr> (+351) 912405749
        </address>

        <address>
            <strong>Email</strong><br>
            <a href="mailto:#">marcelo.t80@gmail.com</a>
        </address>
    </div>
</div>