<div>
    <h3><?php echo $this->t('mteixeira.index.title'); ?></h3>
    <div class="jumbotron">
        <p class="aprestacao"><?php
            echo $this->t('mteixeira.index.text', 
                    array('<a href="http://www2.estgf.ipp.pt/" target="_blank"> ESTGF-IPP- Escola Superior de Tecnologia e Gestão de Felgueiras', '</a>', '<a href="http://www.rocket-internet.de/" target="_blank">', '</a>', '<a href="http://www.glintt.com/" target="_blank">', '</a>', '<a href="http://www.esi.pt/"target="_blank">', '</a>'))
            ?></p>
    </div>
</div>
<div>
    <p><?php echo $this->t('mteixeira.apst'); ?></p>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->t('mteixeira.index.escolar') ?></h3>
            </div>
            <div class="panel-body">
                <img src="<?php echo ($this->basePath() . '/img/1.jpg');?>" alt="" class="img-border">
                <p class="pt20"><?php echo $this->t('percurso.text.acdemico')?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->t('mteixeira.index.profisional') ?></h3>
            </div>
            <div class="panel-body">
                <img src="<?php echo ($this->basePath() . '/img/2.jpg');?>" alt="" class="img-border">
                 <p><?php echo $this->t('mteixeira.tecs')?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->t('mteixeira.index.freelancer') ?></h3>
            </div>
            <div class="panel-body">
                <img src="<?php echo ($this->basePath() . '/img/3.png');?>" alt="" class="img-border">
                <p><?php echo $this->t('mteixeira.acd')?></p>
            </div>
        </div>
    </div>
</div>