<?php
$formContact = $this->form;
$formContact->setAttribute('action', 'review');
$formContact->setAttribute('class', 'form-horizontal');
$formContact->setAttribute('role', 'form');
?>
<div class="row">
    <div class="col-md-12" role="main">
        <div class="bs-docs-section">
            <div class="page-header">
                <h1 id="rec"><?php echo ucfirst($this->t('recomendame.title')); ?></h1>
            </div>
            <p class="lead"><?php echo $this->t('recomendame.text'); ?></p>
        </div>
    </div>
    <?php echo $this->form()->openTag($formContact); ?>
     <?php echo $this->formHidden($formContact->get('csrf')); ?>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label"><?php echo $this->t($formContact->get('email')->getLabel()) . '*' ?></label>
        <div class="col-sm-10">
            <?php $formContact->get('email')->setAttribute('class', 'form-control');?>
            <?php echo $this->formInput($formContact->get('email')); ?>
        </div>
        <?php echo $this->formElementErrors($formContact->get('email')); ?>
    </div>
    <div class="form-group">
        <?php $formContact->get('paragraph')->setLabel($this->t('review.message')); ?>
        <label for="inputPassword3" class="col-sm-2 control-label"><?php echo $formContact->get('paragraph')->getLabel(); ?></label>
        <div class="col-sm-10">
            <?php 
            $formContact->get('paragraph')->setAttribute('rows', '10');
            $formContact->get('paragraph')->setAttribute('class', 'form-control'); ?>
            <?php echo $this->formTextArea($formContact->get('paragraph')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default"><?php echo $this->t($formContact->get('submit')->getValue()); ?></button>
        </div>
    </div>
    
<?php echo $this->form()->closeTag($formContact); ?>
<?php if (count($this->reviews) > 0): ?>
    <div>
        <p><?php echo $this->t('ultimos.comments');?></p>  
        <?php foreach ($this->reviews as $review) : ?>
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-pushpin">&nbsp;</span><?php echo $review->getName();?></h3>
                </div>
                <div class="panel-body">
                  <?php echo $review->getMessage();?>
                </div>
            </div>
        <?php endforeach; ?>
 </div>
<?php endif; ?>
</div>